firstApp/api/urls.py
from django.conf.urls import url
from . import views

app_name = 'api'

urlpatterns = [
    url(r'^$', views.PostListAPIView.as_view(), name='post-list'),
    url(r'^(?P<id>\d+)$',
        views.PostDetailAPIView.as_view(), name='post-detail'),
    url(r'^create/$',
        views.PostCreateAPIView.as_view(), name='post-create'),
    url(r'^(?P<id>\d+)/delete$',
        views.PostDeleteAPIView.as_view(), name='post-delete'),
    url(r'^(?P<id>\d+)/edit$',
        views.PostEditAPIView.as_view(), name='post-edit'),
    url(r'^(?P<id>\d+)/manage$',
        views.PostDeleteEditAPIView.as_view(), name='post-manage'),
]

firstApp/urls.py
from django.conf.urls import url
from . import views

app_name = 'firstApp'

urlpatterns = [
    url(r'^$', views.list, name='list'),
    url(r'^(?P<id>[0-9]{1,3})$', views.detail, name='detail'),
    url(r'^create$', views.create, name='create'),
    url(r'^edit/(?P<id>[0-9]{1,3})$', views.edit, name='edit'),
    url(r'^delete/(?P<id>[0-9]{1,3})$', views.delete, name='delete'),
]

firstSite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('firstApp.urls', namespace='firstApp')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    # API urls
    url(r'^api/', include('firstApp.api.urls', namespace='posts-api')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          documnet_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          documnet_root=settings.STATIC_ROOT)

firstApp/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse


class PostsGroup(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('Post Group')
        verbose_name_plural = _('Posts Group')


class Posts(models.Model):
    # posts_group = models.OneToOneField(PostsGroup)
    # posts_group = models.ManyToManyField(PostsGroup)
    # boolean = models.BooleanField()
    # null_boolean = models.NullBooleanField()
    # date_and_time = models.DateTimeField()
    # email = models.EmailField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_(
        'owner'), blank=True, null=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = RichTextUploadingField(
        _('content'), config_name='default')
    file = models.FileField(
        _('upload file'), upload_to='files/%Y/%m/%d/%r',
        null=True, blank=True)
    image = models.ImageField(
        _('upload image'), upload_to='images/%Y/%m/%d/%r',
        null=True, blank=True)
    update_date_time = models.DateTimeField(
        _('create date'), auto_now_add=True, auto_now=False)
    create_date_time = models.DateTimeField(
        _('update date'), auto_now_add=False, auto_now=True)

    # def __unicode__(self):
    #     return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('firstApp:detail', kwargs={'id': self.id})

    class Meta:
        verbose_name = _('post')
        verbose_name_plural = _('posts')

firstApp/forms.py
from django.forms import ModelForm, Textarea
from . import models


class PostForm(ModelForm):
    class Meta:
        model = models.Posts
        fields = ('title', 'content',)
        widgets = {
            'content': Textarea(attrs={'cols': 100, 'rows': 2})
        }

firstApp/api/views.py
from firstApp.models import Posts
from rest_framework import generics
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import (
    SearchFilter,
    OrderingFilter,
)
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from .permissions import OwnerCanManageOrReadOnly
# from .pagination import (
#     PostPageNumberPagination,
#     PostLimitOffsetPagination,
# )
from rest_framework.permissions import (
    # AllowAny,
    IsAuthenticated,
    # IsAdminUser,  # request.user.is_staff == True
    # IsAuthenticatedOrReadOnly,
)
from firstApp.api.serializers import (
    PostListSerializer,
    PostDetailSerializer,
    PostDeleteSerializer,
    PostUpdateSerializer,
    PostCreateSerializer,
    PostDeleteUpdateSerializer,
)


class PostListAPIView(generics.ListAPIView):
    # queryset = Posts.objects.all()
    serializer_class = PostListSerializer
    filter_backends = (SearchFilter, OrderingFilter, DjangoFilterBackend)
    search_fields = ('title', 'content', 'owner__username')
    ordeing_fields = ('title', 'update_date_time', 'create_date_time')
    # filter_fields = ('title', 'content', 'owner__username')

    def get_queryset(self, *args, **kwargs):
        if self.request.user.is_superuser:
            # superuser can see all posts
            queryset = Posts.objects.all()
        else:
            # otherwise every user can see his posts
            queryset = Posts.objects.filter(owner=self.request.user)

        # Custom search. It is not related to rest_framework
        query = self.request.GET.get('q')
        # q = something
        if query:
            # if user serach for something by 'q' keyword
            queryset = queryset.filter(
                Q(title__icontains=query) |
                Q(content__icontains=query) |
                Q(owner__first_name__icontains=query) |
                Q(owner__last_name__icontains=query) |
                Q(owner__username__icontains=query)
            ).distinct().order_by('-update_date_time')
        return queryset


class PostCreateAPIView(generics.CreateAPIView):
    queryset = Posts.objects.all()
    serializer_class = PostCreateSerializer
    lookup_field = 'id'
    permission_classes = [IsAuthenticated, ]

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)
        # you can send email here and etc.
        # this email sent when serializer create


class PostDetailAPIView(generics.RetrieveAPIView):
    queryset = Posts.objects.all()
    serializer_class = PostDetailSerializer
    lookup_field = 'id'


class PostDeleteAPIView(generics.RetrieveDestroyAPIView):
    queryset = Posts.objects.all()
    serializer_class = PostDeleteSerializer
    lookup_field = 'id'
    permission_classes = [OwnerCanManageOrReadOnly, ]

    def perform_destroy(self, serializer):
        # just owner can delete post
        if serializer.owner != self.request.user:
            raise PermissionDenied
        else:
            serializer.delete()


class PostEditAPIView(generics.RetrieveUpdateAPIView):
    queryset = Posts.objects.all()
    serializer_class = PostUpdateSerializer
    lookup_field = 'id'
    permission_classes = [OwnerCanManageOrReadOnly, ]

    def perform_update(self, serializer):
        serializer.save(owner=self.request.user)
        # you can send email here and etc.
        # this email sent when serializer create


class PostDeleteEditAPIView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Posts.objects.all()
    serializer_class = PostDeleteUpdateSerializer
    lookup_field = 'id'
    permission_classes = [OwnerCanManageOrReadOnly, ]


# with use import from the django shell
"""
from firstApp.models import Posts
from firstApp.api.serializers import PostDetailSerializer

data = {
    'title': 'this is my title',
    'content': 'this is my content',
    'owner': 1,
}
new_item = PostDetailSerializer(date=data)

if new_item.is_valid():
    new_item.save()
else:
    print(new_item.errors)
"""

firstApp/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from firstApp.models import Posts
from django.http import Http404
from django.contrib import messages
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.utils.translation import ugettext_lazy as _
from .forms import PostForm


def list(request):
    posts = Posts.objects.all()
    paginator = Paginator(posts, 25)  # Show 25 posts per page
    page = request.GET.get('page')

    try:
        posts = paginator.get_page(page)
    except PageNotAnInteger:
        # If page not an integer, deliver first page.
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g 9999), deliver last page of results.
        posts = paginator.page(paginator.num_pages)

    return render(request, 'list.html', {'posts': posts})


def detail(request, id=None):
    post = get_object_or_404(Posts, id=id)
    return render(request, 'detail.html', {'post': post})


def create(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404

    create_form = PostForm(request.POST or None, request.FILES or None,)
    if create_form.is_valid():
        create_form.save(commit=False)
        create_form.user = request.user
        post = create_form.save()
        messages.success(request, _('created successfully!!!'),
                         extra_tags='alert alert-success')
        return HttpResponseRedirect(post.get_absolute_url())
    return render(request, 'create.html', {'form': create_form})


def edit(request, id=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404

    post = get_object_or_404(Posts, id=id)
    edit_form = PostForm(request.POST or None,
                         request.FILES or None, instance=post)
    if edit_form.is_valid():
        edit_form.save()
        messages.success(request, _('updated successfully!!!'),
                         extra_tags='alert alert-success')
        return HttpResponseRedirect(post.get_absolute_url())
    return render(request, 'edit.html', {'form': edit_form})


def delete(request, id=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404

    post = get_object_or_404(Posts, id=id)
    if post.delete():
        messages.success(request, _('item deleted successfully!!!'),
                         extra_tags='alert alert-success')
        return HttpResponseRedirect('/')
    return render(request, 'detail.html', {'post': post})

firstApp/templates/base_firstApp.html
{% load static %}

<!DOCTYPE html>

<html>

    <title>

        {% block head %}
        Welcome to First Site
        {% endblock head %}

    </title>

    <head>
        
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        {% block css %}

            <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'css/custom_style.css' %}">

        {% endblock css %}
        
    </head>

    <body>

        {% block navbar %}

            <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
                {# <!-- Brand --> #}
                {# <a class="navbar-link" href="#">Logo</a> #}

                <!-- Links -->
                <ul class="navbar-nav">
                  
                    <!-- Home -->
                    <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                    </li>

                    {% if request.user.is_superuser or request.user.is_staff or request.user.is_authenticated %}

                    <!-- Dashboard -->
                    <li class="nav-item">
                      <a class="nav-link" href="/admin">Dashboard</a>
                    </li>

                    <!-- Create Post -->
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'firstApp:create' %}">Create Post</a>
                    </li>

                    <!-- Logout -->
                    <li class="nav-item">
                      <a class="nav-link" href="/admin/logout">Logout</a>
                    </li>

                    {% else %}

                    <!-- Login -->
                    <li class="nav-item">
                      <a class="nav-link" href="/admin">Login</a>
                    </li>

                    {% endif %}
                    
                    <!-- Search Form-->
                    <li>
                        
                        <form action="" method="GET" class="form-inline pull-lg-left pull-md-left hidden-md-down" >
                            <input name="q" class="form-control mr-sm-2" type="text" placeholder="Search">
                            <button class="btn btn-success" type="submit">Search</button>
                        </form>

                    </li>

                </ul>
            </nav>

        {% endblock navbar %}

        <div class="container" class="rtl">

            {% block messages %}

                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>

                {% endif %}
          
            {% endblock messages %}

            {% block search_result %}
                
                {% for result in search_result %}

                    <div class="row">

                        <div class="col-12">
                                    
                            <div class="card">

                                <div class="card-body">

                                    <h4 class="card-title">

                                        <a href="{{ result.get_absolute_url }}">
                                            {{result.title}}
                                        </a>

                                    </h4>

                                    <p class="card-text">
                                        {{result.content|safe|truncatechars_html:200}}
                                        <small>
                                        {{result.update_date_time}}
                                        </small>
                                    </p>

                                    <a href="{% url 'firstApp:edit' id=result.id %}" button type="button" class="btn btn-outline-warning btn-sm" class="card-link">Edit Post</a>

                                    <a href="{% url 'firstApp:delete' id=result.id %}" button type="button" class="btn btn-outline-danger btn-sm" class="card-link">Delete Post</a>

                                </div>

                            </div>
                                
                        </div>

                    </div>
                    
                {% endfor %}

            {% endblock search_result %}
            <hr>

            {% block content %}

            {% endblock content %}

        </div>

        {% block js %}

        <script type="text/javascript", src="{% static 'js/jquery.min.js' %}"></script>
        <script type="text/javascript", src="{% static 'js/popper.min.js' %}"></script>
        <script type="text/javascript", src="{% static 'js/bootstrap.min.js' %}"></script>

        {% endblock js %}

    </body>

</html>

firstApp/templates/create.html
{% extends "base_firstApp.html" %}
{% load i18n %}

{% block head %}
    {{ block.super }} | Create
{% endblock head %}

{% block content %}
    <br>
    <form action="" method="post" enctype="multipart/form-data" >

        {% csrf_token %}

        {{ form.as_p }}
        <button class="btn btn-primary" type="Submit">{% trans "save" %}</button>

    </form>
    
{% endblock content %}

firstApp/templates/delete.html
{% extends "base_firstApp.html" %}

{% block head %}
	{{ block.super }} | Delete
{% endblock head %}

<h1>Delete</h1>

firstApp/templates/detail.html
{% extends "base_firstApp.html" %}

{% block head %}
    {{ block.super }} | Detail
{% endblock head %}

{% block content %}

        <br>
            <div>
                <h1>
                    {{post.title}}
                </h1>
                <h7 class="rtl">
                    {{post.update_date_time}}
                </h7>
                <p>
                    {{post.content|safe}}
                </p>
            </div>
        <hr>

{% endblock content %}

firstApp/templates/edit.html
{% extends "base_firstApp.html" %}
{% load i18n %}

{% block head %}
    {{ block.super }} | Edit
{% endblock head %}

{% block content %}
    <br>
    <form action="" method="post" enctype="multipart/form-data" >

        {% csrf_token %}

        {{ form.as_p }}
        <button class="btn btn-primary" type="Submit">{% trans "save" %}</button>

    </form>

{% endblock content %}

firstApp/templates/list.html
{% extends "base_firstApp.html" %}

{% block head %}
    {{ block.super }} | List
{% endblock head %}

{% block content %}

    {% for post in posts %}
        <br>
        <div class="row">

            <div class="col-6">
                        
                <div class="card">

                    <div class="card-body">

                        <h4 class="card-title">

                            <a href="{{ post.get_absolute_url }}">
                                {{post.title}}
                            </a>

                        </h4>

                        <p class="card-text">
                            {{post.content|safe|truncatechars_html:200}}
                            <small>
                            {{post.update_date_time}}
                            </small>
                        </p>

                        <a href="{% url 'firstApp:edit' id=post.id %}" button type="button" class="btn btn-outline-warning btn-sm" class="card-link">Edit Post</a>

                        <a href="{% url 'firstApp:delete' id=post.id %}" button type="button" class="btn btn-outline-danger btn-sm" class="card-link">Delete Post</a>

                    </div>

                </div>
                    
            </div>

        </div>

    {% endfor %}
    <br>
    <div class="row">
        
        <div class="text-center">
        
            <div class="pagination">
                <span class="step-links">
                    {% if posts.has_previous %}
                        <a class="btn btn-default btn-sm" href="?page=1">&laquo; first</a>
                        <a class="btn btn-default btn-sm" href="?page={{ posts.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
                    </span>

                    {% if posts.has_next %}
                        <a class="btn btn-default btn-sm" href="?page={{ posts.next_page_number }}">next</a>
                        <a class="btn btn-default btn-sm" href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>

        </div>

    </div>
    
    <br>
{% endblock content %}  